name: 'chess_com_bi'
version: '1.0.0'

profile: 'chess_com_bi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  data_conversion:
    utc_to_target_timezone: "'Europe/Paris'"
  game_phases:
    end_early_game_move: 15
    end_mid_game_move: 30
  elo_range:
    low: 600
    mid: 700
  score_thresholds:
    variance_score_massive_blunder: 600
    variance_score_blunder: 250
    variance_score_mistake: 100
    score_balanced_limit: 200
    even_score_limit: 150
    should_win_score: 700
  data_scope:
    first_end_date: "'2024-10-01'"
  datamart:
    min_games_played: 20

models:
  chess_com_bi:
    intermediate:
      +materialized: view
      +schema: intermediate
    reporting:
      +materialized: view
      +schema: reporting
    datamart:
      +materialized: view
      +schema: datamart
seeds:
  chess_com_bi:
    schema: staging