name: 'chess_com_bi'
version: '1.0.0'

profile: 'chess_com_bi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  data_conversion:
    utc_to_target_timezone: "'Europe/Paris'"
  game_phases:
      early:
        end_game_move: 15
        name: "'1-Early Game'"
      mid: 
        end_game_move: 35
        name: "'2-Mid Game'"
      late: 
        end_game_move: 65
        name: "'3-Late Game'"
      very_late:
        name: "'4-Very Late Game'"

  elo_range: [400,600,800,1000,1200,1400,1600,1800]
  score_thresholds:
    variance_score_massive_blunder: 600
    variance_score_blunder: 250
    variance_score_mistake: 100
    score_balanced_limit: 200
    even_score_limit: 150
  should_win_range:
    low: 300
    mid: 500
  data_scope:
    month_history_depth: 5
    time_class: ['blitz', 'rapid', 'bullet']
  datamart:
    min_games_played: 20

models:
  chess_com_bi:
    intermediate:
      +materialized: view
      +schema: intermediate
      +docs:
        node_color: '#696969' # Silver
    reporting:
      +materialized: view
      +schema: reporting
      +docs:
        node_color: '#C5A939' # Gold
    datamart:
      +materialized: view
      +schema: datamart
      +docs:
        node_color: '#B59410' # Darker Gold
seeds:
  chess_com_bi:
    schema: staging
    +docs:
      node_color: '#5fb825' # Light Green (like DBT seeds)