chess_com_bi:
  outputs:
    prod:
      dataset: sandbox_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./keyfile.json
      location: US
      method: service-account
      priority: interactive
      project: chesscom-451104
      threads: 4
      type: bigquery
  target: prod