api:
  usernames:
    - piwi100
    - Zundorn
    - leprechess
    - bgdu33
    - quentinusdesbois
    - romainpct
    - gokhvttttgxdddhjkig345
    - yorek99
    # Reddit users:
    - dapipshark
    - sajmansito
    - beng_16
    - 62westwallaby
    - xn312fx
    - sluciano3
    - glenmsheppard
    - jaebr8
    - max_otto_stierlitz
    - kkgttv
    - chesstrogen
    - typicalplayer11
    - meachumz
    - febar92
    - monksc
    - allem34
    - nadis_z
    - rogerick
    - babystinkboog
    - nyylp844
    - jamesi05
    - somedrewguy
    - voidlr
    - veddntt
    - bonbonfrosch
    - karthik704
    - grosgogtjopie
  email: cassado01@gmail.com
  min_archive: "2025/02"

bigquery:
  config:
    dataset_id: "chesscom-451104.staging"
    project_id: "chesscom-451104"
  tables:
    games_prefix: "games_infos_"
    games_moves_prefix: "games_moves_"
