name: Run dbt in Docker

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Write Google Cloud credentials
        run: echo '${{ secrets.GCS_KEYFILE }}' > keyfile.json

      - name: Build and run Docker container
        run: |
          docker build -t dbt-container .
          docker run --rm \
            -v ${{ github.workspace }}/keyfile.json:/keyfile.json \
            dbt-container python3 scripts/your_script.py
